// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqcxumybcliqbnyluagg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxY3h1bXliY2xpcWJueWx1YWdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxOTMwMDIsImV4cCI6MjA1OTc2OTAwMn0.2iOckzmnFEyWMbsYe8noMaKewSw15VDKOVQQEFzr2GI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);